# This configuration file should contain all required configuration parameters
# for the phylogenetic workflow to run to completion.
#
# Define optional config parameters with their default values here so that users
# do not have to dig through the workflows to figure out the default values

strain_id_field: "accession"
display_strain_field: "strain"

filter:
  group_by: "country year month"
  sequences_per_group: 40
  min_date: 1900
  min_length: 11200

refine:
  coalescent: "opt"
  date_inference: "marginal"
  clock_filter_iqd: 4

ancestral:
  inference: "joint"

traits:
  columns: "region country insertion6738"
  sampling_bias_correction: 3